version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/cli"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/proxy"
    schedule:
      interval: "weekly"
