default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 50
  workers:
    - queues: [ default ]
      threads: 2
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 2) %>
      polling_interval: 1
    - queues: [ disco ]
      threads: 1
      processes: 1
      polling_interval: 2

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
