name = "feeeed-dispatcher"
main = "src/index.ts"
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "b79f5bd5b43c4e85ad673a125ff03cea"
localConnectionString = "postgres://postgres:password@localhost:5432/feeeed_development"
